bin_PROGRAMS = gork
gork_SOURCES = main.c relay.c relay.h tui.c tui.h mcp.c mcp.h \
                cJSON/cJSON.c cJSON/cJSON.h
EXTRA_DIST = README.md gork.spec debian/changelog debian/control \
             debian/rules debian/source/format

iconsdir = $(datadir)/icons/hicolor/256x256/apps
dist_icons_DATA = images/gork.png
